export const supportedLanguages = ['en', 'de', 'fr'] as const;

export type Language = (typeof supportedLanguages)[number];

export const defaultLanguage: Language = 'en';

const messages = {
  en: {
    episodeNumber: 'VIDEO #001',
    titleLineOne: 'Why Your API Gets Faster',
    titleLineTwo: 'After Adding Redis',
    language: 'Language',
    request: 'Request',
    application: 'Application',
    database: 'Database',
    requestOrigin: 'Request origin',
    routingLogic: 'Routing logic',
    sourceOfTruth: 'Source of truth',
    beforeRedis: 'Before Redis',
    afterRedis: 'After Redis',
    sameRequest: 'Same request. Same data.',
    fastLookup: 'Fast lookup',
    whatChanged: 'What changed?',
    mystery: 'The mystery',
    latencyQuestion: 'Where did the 180 ms go?',
    illustrativeBreakdown: 'Illustrative breakdown',
    dbNetwork: 'DB/network',
    databaseWork: 'Database work',
    serialization: 'Serialization',
    other: 'Other',
    latencyTakeaway: 'Most of the time is spent doing database work.',
    misconceptionQuestion: 'So Redis made the database faster?',
    stoppedRepeatingWork: 'We stopped repeating some of the work.',
    sameWorkAgain: 'Same work. Again.',
    readyShelfIntro: 'Already prepared. Waiting on the shelf.',
    chefDidntCookAtAll: "The chef didn't cook at all.",
    redisSkipsRepeatedWork: 'Redis answers repeated requests without repeating database work.',
    cacheMissRequestArrives: 'A request reaches the application.',
    cacheMissCheckRedis: 'Before touching the Database, the application checks Redis.',
    cacheMissNotFound: 'But this time, Redis does not have the result.',
    cacheMissAskDatabase: 'So the application still has to ask the Database.',
    cacheMissExpensiveWork: 'The expensive work still happens on this request.',
    cacheMissResultReturns: 'The Database returns the result.',
    cacheMissStoreInRedis: 'Before responding, the application stores that result in Redis.',
    cacheMissClosing: 'The first request was still expensive. But now Redis has the result ready for next time.',
    cacheHitRequestArrives: 'Now the same request arrives again.',
    cacheHitCheckRedis: 'The application checks Redis first.',
    cacheHitFound: 'This time, Redis already has the result.',
    cacheHitDatabaseSkipped: 'The Database is skipped entirely.',
    cacheHitResultReturns: 'The cached result comes straight back to the application.',
    cacheHitFastResponse: 'Now the response returns much faster — about 8 ms after Redis.',
    cacheHitClosing: 'The Database did not get faster. We simply did not need it this time.',
    whyFastBridge: 'Why is that path so much faster?',
    whyFastPreparedResult: 'Redis already holds a prepared result.',
    whyFastSimpleLookup: 'Finding it is a simple, direct lookup — not a query.',
    whyFastInMemory: 'That lookup happens in memory, which helps — but it is not the whole story.',
    whyFastWorkAvoided: 'The expensive Database work behind that result is skipped entirely.',
    whyFastModernDbMemory: 'Modern databases also use memory heavily.',
    whyFastClosing: 'Not memory magic — we simply avoided repeated work.',
    cacheEverythingBridge: 'So... why not avoid repeated work everywhere?',
    cacheEverythingPunch: 'CACHE EVERYTHING!',
    cacheEverythingCorrection: 'Not so fast.',
    cacheEverythingCosts: 'More memory. More stale data. More to keep in sync.',
    cacheEverythingNotEveryRequest:
      'Not every request is expensive enough to justify caching — and misses still happen.',
    cacheEverythingDecisionRule:
      'Cache where avoiding repeated expensive work is worth the tradeoff.',
    staleCacheBridge: 'What does "stale data" actually mean?',
    staleCacheDatabaseChanges: 'The Database record changes.',
    staleCacheRedisOld: 'But Redis still holds the old value.',
    staleCacheFastResponse: 'The application reads Redis — and returns that answer fast.',
    staleCacheJoke: 'Wrong answer. Very fast.',
    staleCacheTakeaway: 'Caching reuses old work. That’s also how it can become stale.',
    staleCacheRoleCurrent: 'CURRENT',
    staleCacheRoleCachedCopy: 'CACHED COPY',
    cacheCostsBridge: 'And stale data is only one of the costs.',
    cacheCostsFreshness: 'Freshness',
    cacheCostsFreshnessCaption:
      'It needs expiration and invalidation — so data does not sit unchecked forever.',
    cacheCostsCapacity: 'Capacity',
    cacheCostsCapacityCaption: 'It consumes memory — and memory is not infinite.',
    cacheCostsResilience: 'Resilience',
    cacheCostsResilienceCaption: 'Sometimes it misses. Sometimes it fails. Both need a plan.',
    cacheCostsOperations: 'Operations',
    cacheCostsOperationsCaption: 'Someone has to watch it, and something has to run it.',
    cacheCostsClosing:
      'Caching trades repeated work for extra state, infrastructure, and coordination.',
  },
  de: {
    episodeNumber: 'VIDEO #001',
    titleLineOne: 'Warum deine API schneller wird',
    titleLineTwo: 'wenn du Redis hinzufügst',
    language: 'Sprache',
    request: 'Anfrage',
    application: 'Anwendung',
    database: 'Datenbank',
    requestOrigin: 'Anfragequelle',
    routingLogic: 'Routing-Logik',
    sourceOfTruth: 'Datenquelle',
    beforeRedis: 'Vor Redis',
    afterRedis: 'Nach Redis',
    sameRequest: 'Gleiche Anfrage. Gleiche Daten.',
    fastLookup: 'Schneller Zugriff',
    whatChanged: 'Was hat sich geändert?',
    mystery: 'Das Rätsel',
    latencyQuestion: 'Wohin gehen die 180 ms?',
    illustrativeBreakdown: 'Beispielhafte Aufschlüsselung',
    dbNetwork: 'DB/Netzwerk',
    databaseWork: 'Datenbankarbeit',
    serialization: 'Serialisierung',
    other: 'Sonstiges',
    latencyTakeaway: 'Der größte Teil der Zeit entfällt auf Datenbankarbeit.',
    misconceptionQuestion: 'Hat Redis also die Datenbank schneller gemacht?',
    stoppedRepeatingWork: 'Wir wiederholen einen Teil der Arbeit nicht mehr.',
    sameWorkAgain: 'Dieselbe Arbeit. Noch einmal.',
    readyShelfIntro: 'Bereits zubereitet. Wartet im Regal.',
    chefDidntCookAtAll: 'Der Koch hat gar nicht gekocht.',
    redisSkipsRepeatedWork:
      'Redis beantwortet wiederholte Anfragen, ohne die Datenbankarbeit zu wiederholen.',
    cacheMissRequestArrives: 'Eine Anfrage erreicht die Anwendung.',
    cacheMissCheckRedis: 'Bevor die Anwendung die Datenbank anspricht, prüft sie Redis.',
    cacheMissNotFound: 'Doch diesmal hat Redis das Ergebnis nicht.',
    cacheMissAskDatabase: 'Also muss die Anwendung trotzdem die Datenbank fragen.',
    cacheMissExpensiveWork: 'Die teure Arbeit fällt bei dieser Anfrage trotzdem an.',
    cacheMissResultReturns: 'Die Datenbank liefert das Ergebnis zurück.',
    cacheMissStoreInRedis: 'Bevor sie antwortet, speichert die Anwendung das Ergebnis in Redis.',
    cacheMissClosing:
      'Die erste Anfrage war trotzdem teuer. Aber jetzt hat Redis das Ergebnis für das nächste Mal bereit.',
    cacheHitRequestArrives: 'Jetzt trifft dieselbe Anfrage erneut ein.',
    cacheHitCheckRedis: 'Die Anwendung prüft zuerst Redis.',
    cacheHitFound: 'Diesmal hat Redis das Ergebnis bereits.',
    cacheHitDatabaseSkipped: 'Die Datenbank wird komplett übersprungen.',
    cacheHitResultReturns: 'Das zwischengespeicherte Ergebnis geht direkt zurück an die Anwendung.',
    cacheHitFastResponse: 'Jetzt kommt die Antwort viel schneller zurück – etwa 8 ms nach Redis.',
    cacheHitClosing: 'Die Datenbank wurde nicht schneller. Wir haben sie diesmal einfach nicht gebraucht.',
    whyFastBridge: 'Warum ist dieser Pfad so viel schneller?',
    whyFastPreparedResult: 'Redis hat das Ergebnis bereits vorbereitet.',
    whyFastSimpleLookup: 'Es zu finden ist ein einfacher, direkter Zugriff — keine Abfrage.',
    whyFastInMemory:
      'Dieser Zugriff geschieht im Arbeitsspeicher, was hilft — aber das ist nicht die ganze Geschichte.',
    whyFastWorkAvoided: 'Die teure Datenbankarbeit hinter diesem Ergebnis entfällt vollständig.',
    whyFastModernDbMemory: 'Auch moderne Datenbanken nutzen intensiv Arbeitsspeicher.',
    whyFastClosing: 'Keine Speicher-Magie — wir haben nur wiederholte Arbeit vermieden.',
    cacheEverythingBridge: 'Also... warum nicht überall wiederholte Arbeit vermeiden?',
    cacheEverythingPunch: 'ALLES CACHEN!',
    cacheEverythingCorrection: 'Nicht so schnell.',
    cacheEverythingCosts: 'Mehr Speicher. Mehr veraltete Daten. Mehr Synchronisationsaufwand.',
    cacheEverythingNotEveryRequest:
      'Nicht jede Anfrage lohnt sich — und Fehltreffer passieren trotzdem.',
    cacheEverythingDecisionRule:
      'Cachen, wo das Vermeiden teurer, wiederholter Arbeit den Aufwand wert ist.',
    staleCacheBridge: 'Was bedeutet „veraltete Daten“ eigentlich?',
    staleCacheDatabaseChanges: 'Der Datenbankeintrag ändert sich.',
    staleCacheRedisOld: 'Aber Redis hat noch den alten Wert.',
    staleCacheFastResponse: 'Die Anwendung liest Redis — und liefert diese Antwort schnell zurück.',
    staleCacheJoke: 'Falsche Antwort. Sehr schnell.',
    staleCacheTakeaway: 'Caching nutzt alte Arbeit wieder. Genau so kann sie veralten.',
    staleCacheRoleCurrent: 'AKTUELL',
    staleCacheRoleCachedCopy: 'GECACHT',
    cacheCostsBridge: 'Und veraltete Daten sind nur ein Teil der Kosten.',
    cacheCostsFreshness: 'Aktualität',
    cacheCostsFreshnessCaption:
      'Es braucht Ablaufzeiten und Invalidierung — damit Daten nicht dauerhaft ungeprüft bleiben.',
    cacheCostsCapacity: 'Kapazität',
    cacheCostsCapacityCaption: 'Es verbraucht Arbeitsspeicher — und der ist nicht unbegrenzt.',
    cacheCostsResilience: 'Resilienz',
    cacheCostsResilienceCaption:
      'Manchmal gibt es einen Fehltreffer. Manchmal fällt es aus. Beides braucht einen Plan.',
    cacheCostsOperations: 'Betrieb',
    cacheCostsOperationsCaption: 'Jemand muss es beobachten, und etwas muss es betreiben.',
    cacheCostsClosing:
      'Caching tauscht wiederholte Arbeit gegen zusätzlichen Zustand, Infrastruktur und Koordination.',
  },
  fr: {
    episodeNumber: 'VIDÉO N° 001',
    titleLineOne: 'Pourquoi votre API accélère',
    titleLineTwo: 'avec Redis',
    language: 'Langue',
    request: 'Requête',
    application: 'Application',
    database: 'Base de données',
    requestOrigin: 'Origine de la requête',
    routingLogic: 'Logique de routage',
    sourceOfTruth: 'Source de vérité',
    beforeRedis: 'Avant Redis',
    afterRedis: 'Après Redis',
    sameRequest: 'Même requête. Mêmes données.',
    fastLookup: 'Accès rapide',
    whatChanged: 'Qu’est-ce qui a changé ?',
    mystery: 'Le mystère',
    latencyQuestion: 'Où sont passées les 180 ms ?',
    illustrativeBreakdown: 'Répartition illustrative',
    dbNetwork: 'BD/réseau',
    databaseWork: 'Travail de la base de données',
    serialization: 'Sérialisation',
    other: 'Autre',
    latencyTakeaway: 'La majeure partie du temps est consacrée au travail de la base de données.',
    misconceptionQuestion: 'Redis a donc rendu la base plus rapide ?',
    stoppedRepeatingWork: 'Nous avons arrêté de répéter une partie du travail.',
    sameWorkAgain: 'Le même travail. Encore.',
    readyShelfIntro: 'Déjà préparé. En attente sur l’étagère.',
    chefDidntCookAtAll: "Le chef n'a pas du tout cuisiné.",
    redisSkipsRepeatedWork:
      'Redis répond aux requêtes répétées sans répéter le travail de la base de données.',
    cacheMissRequestArrives: "Une requête arrive jusqu'à l'application.",
    cacheMissCheckRedis:
      "Avant de contacter la base de données, l'application vérifie Redis.",
    cacheMissNotFound: "Mais cette fois, Redis n'a pas le résultat.",
    cacheMissAskDatabase: "L'application doit donc quand même interroger la base de données.",
    cacheMissExpensiveWork: 'Le travail coûteux a quand même lieu pour cette requête.',
    cacheMissResultReturns: 'La base de données renvoie le résultat.',
    cacheMissStoreInRedis:
      "Avant de répondre, l'application stocke ce résultat dans Redis.",
    cacheMissClosing:
      "La première requête a quand même coûté cher. Mais Redis a maintenant le résultat prêt pour la prochaine fois.",
    cacheHitRequestArrives: 'Maintenant, la même requête arrive à nouveau.',
    cacheHitCheckRedis: "L'application vérifie d'abord Redis.",
    cacheHitFound: 'Cette fois, Redis a déjà le résultat.',
    cacheHitDatabaseSkipped: 'La base de données est entièrement contournée.',
    cacheHitResultReturns: 'Le résultat mis en cache revient directement à l’application.',
    cacheHitFastResponse: 'La réponse revient maintenant beaucoup plus vite — environ 8 ms après Redis.',
    cacheHitClosing:
      "La base de données n'est pas devenue plus rapide. Nous n'en avions simplement pas besoin cette fois.",
    whyFastBridge: 'Pourquoi ce chemin est-il tellement plus rapide ?',
    whyFastPreparedResult: 'Redis a déjà le résultat préparé.',
    whyFastSimpleLookup: 'Le trouver est un accès simple et direct — pas une requête.',
    whyFastInMemory:
      "Cet accès se fait en mémoire, ce qui aide — mais ce n'est pas toute l'histoire.",
    whyFastWorkAvoided:
      'Le travail coûteux de la base de données derrière ce résultat est entièrement évité.',
    whyFastModernDbMemory: 'Les bases de données modernes utilisent aussi beaucoup la mémoire.',
    whyFastClosing: 'Pas de magie mémoire — nous avons simplement évité un travail répété.',
    cacheEverythingBridge: 'Alors... pourquoi ne pas éviter le travail répété partout ?',
    cacheEverythingPunch: 'TOUT METTRE EN CACHE !',
    cacheEverythingCorrection: 'Pas si vite.',
    cacheEverythingCosts: 'Plus de mémoire. Plus de données obsolètes. Plus à synchroniser.',
    cacheEverythingNotEveryRequest:
      "Toutes les requêtes ne valent pas la peine d'être mises en cache — et il y a encore des échecs.",
    cacheEverythingDecisionRule:
      'Mettez en cache là où éviter un travail répété et coûteux en vaut la peine.',
    staleCacheBridge: 'Que signifie vraiment une « donnée obsolète » ?',
    staleCacheDatabaseChanges: "L'enregistrement de la base de données change.",
    staleCacheRedisOld: "Mais Redis a toujours l'ancienne valeur.",
    staleCacheFastResponse: "L'application lit Redis — et renvoie cette réponse rapidement.",
    staleCacheJoke: 'Mauvaise réponse. Très rapide.',
    staleCacheTakeaway: 'La mise en cache réutilise un ancien travail. C’est aussi comme cela qu’elle devient obsolète.',
    staleCacheRoleCurrent: 'ACTUEL',
    staleCacheRoleCachedCopy: 'COPIE EN CACHE',
    cacheCostsBridge: "Et les données obsolètes ne sont qu'un des coûts.",
    cacheCostsFreshness: 'Fraîcheur',
    cacheCostsFreshnessCaption:
      "Il faut de l'expiration et de l'invalidation — pour que les données ne restent pas indéfiniment sans vérification.",
    cacheCostsCapacity: 'Capacité',
    cacheCostsCapacityCaption: "Il consomme de la mémoire — et la mémoire n'est pas infinie.",
    cacheCostsResilience: 'Résilience',
    cacheCostsResilienceCaption:
      "Parfois, c'est un échec de cache. Parfois, une panne. Les deux demandent un plan.",
    cacheCostsOperations: 'Opérations',
    cacheCostsOperationsCaption: 'Quelqu’un doit le surveiller, et quelque chose doit le faire fonctionner.',
    cacheCostsClosing:
      "La mise en cache échange du travail répété contre plus d'état, d'infrastructure et de coordination.",
  },
} as const;

export type MessageKey = keyof (typeof messages)[typeof defaultLanguage];

export const translate = (language: Language, key: MessageKey): string =>
  messages[language]?.[key] ?? messages[defaultLanguage][key];
